services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"  # Ensure it matches Flask's exposed portvolumes:
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env  # Load environment variables

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - "5173:80"  # Assuming frontend runs on port 3000
    depends_on:
      - backend  # Ensure backend starts first
#    develop:
#      watch:
#        - action: sync
#          path: ./frontend/src